// <auto-generated />
using System;
using InformeTorneo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformeTorneo.Migrations
{
    [DbContext(typeof(TorneoContext))]
    [Migration("20221119201302_agregacionTorneo1")]
    partial class agregacionTorneo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InformeTorneo.Models.Equipo", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiferenciaDeGoles")
                        .HasColumnType("int");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("int");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("int");

                    b.Property<int?>("InformeId")
                        .HasColumnType("int");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Nombre");

                    b.HasIndex("InformeId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("InformeTorneo.Models.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("torneoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("torneoNombre");

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("InformeTorneo.Models.Torneo", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.HasKey("Nombre");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("InformeTorneo.Models.Equipo", b =>
                {
                    b.HasOne("InformeTorneo.Models.Informe", null)
                        .WithMany("equipos")
                        .HasForeignKey("InformeId");
                });

            modelBuilder.Entity("InformeTorneo.Models.Informe", b =>
                {
                    b.HasOne("InformeTorneo.Models.Torneo", "torneo")
                        .WithMany()
                        .HasForeignKey("torneoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("torneo");
                });

            modelBuilder.Entity("InformeTorneo.Models.Informe", b =>
                {
                    b.Navigation("equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
